name: Test project
on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: true

jobs:
  test-python:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install python dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev

      - name: Run python linters
        run: |
          pipenv run black --check .
          pipenv run flake8 .
          pipenv run isort --check .

      - name: Run python tests
        run: PIPENV_DOTENV_LOCATION=.env.cicd pipenv run pytest
